# Generated by Django 4.1.1 on 2022-09-29 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("versioning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='versioning.revision')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='versioning.revision')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(null=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='pages.page')),
            ],
        ),
    ]
