# Generated by Django 4.1.1 on 2022-10-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerevision',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='revisions', to='pages.page'),
        ),
    ]
