# Generated by Django 4.1.1 on 2022-10-26 04:26

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0005_events_middlewareevents'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_operation', models.IntegerField(choices=[(1, 'Insert'), (2, 'Update'), (3, 'Delete')], null=True)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='page',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pages_pageevent" ("body", "id", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "published_at", "title", "url") VALUES (NEW."body", NEW."id", NEW."parent_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", 1, NEW."published_at", NEW."title", NEW."url"); RETURN NULL;', hash='382909e09cb82cfa4140eef363b40a5cf456b9f9', operation='INSERT', pgid='pgtrigger_snapshot_insert_b7ea6', table='pages_page', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='page',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "pages_pageevent" ("body", "id", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "published_at", "title", "url") VALUES (NEW."body", NEW."id", NEW."parent_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", 2, NEW."published_at", NEW."title", NEW."url"); RETURN NULL;', hash='f17fa151a4e44bd09ad430a5cdf640b82ec1ed88', operation='UPDATE', pgid='pgtrigger_snapshot_update_8876e', table='pages_page', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='page',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pages_pageevent" ("body", "id", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "published_at", "title", "url") VALUES (NEW."body", NEW."id", NEW."parent_id", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", 3, NEW."published_at", NEW."title", NEW."url"); RETURN NULL;', hash='71f15b8a4539fcd1ddf2babb0135934881c66f3e', operation='DELETE', pgid='pgtrigger_snapshot_delete_64104', table='pages_page', when='AFTER')),
        ),
        migrations.AddField(
            model_name='pageevent',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='pages.page'),
        ),
        migrations.AddField(
            model_name='pageevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='pageevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='pages.page'),
        ),
    ]
