# Generated by Django 4.1.1 on 2022-10-26 04:28

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pageevent_page_snapshot_insert_page_snapshot_update_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='page',
            name='snapshot_delete',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='page',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "pages_pageevent" ("body", "id", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "published_at", "title", "url") VALUES (OLD."body", OLD."id", OLD."parent_id", _pgh_attach_context(), NOW(), \'snapshot\', OLD."id", 3, OLD."published_at", OLD."title", OLD."url"); RETURN NULL;', hash='72ddcbf670b336daf9af127e722c6838a3af886c', operation='DELETE', pgid='pgtrigger_snapshot_delete_64104', table='pages_page', when='AFTER')),
        ),
    ]
