# Generated by Django 4.1.1 on 2022-11-02 00:35

from django.db import migrations
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_page_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='page',
            name='soft_delete',
        ),
    ]
